---
vxlan:
  topology:
    switches:
      - name: Site-3_Spine2-data
        # serial_number: PRE9KTYHLTZL8N
        serial_number: 9KTYHLTZL8N
        role: spine
        management:
          default_gateway_v4: 192.168.106.1
          management_ipv4_address: 192.168.106.6
          subnet_mask_ipv4: 24
        poap:
          preprovision:
            model: N9K-C9300v
            serial_number: PRE9KTYHLTZL8N
            version: 10.5(2)
            modulesModel: [N9K-X9364v, N9K-vSUP]
        interfaces:
          - name: loopback0
            description: "Routing loopback interface"
            mode: fabric_loopback
            vrf: default
            ipv4_address:  10.2.14.6
          - name: Ethernet1/4
            enabled: false
            mode: access
          - name: Ethernet1/5
            enabled: false
            mode: access
          - name: Ethernet1/6
            enabled: false
            mode: access
          - name: Ethernet1/7
            enabled: false
            mode: access
          - name: Ethernet1/8
            enabled: false
            mode: access
          - name: Ethernet1/9
            enabled: false
            mode: access
          - name: Ethernet1/10
            enabled: false
            mode: access
          - name: Ethernet1/11
            enabled: false
            mode: access
          - name: Ethernet1/12
            enabled: false
            mode: access
          - name: Ethernet1/13
            enabled: false
            mode: access
          - name: Ethernet1/14
            enabled: false
            mode: access
          - name: Ethernet1/15
            enabled: false
            mode: access
          - name: Ethernet1/16
            enabled: false
            mode: access
          - name: Ethernet1/17
            enabled: false
            mode: access
          - name: Ethernet1/18
            enabled: false
            mode: access
          - name: Ethernet1/19
            enabled: false
            mode: access
          - name: Ethernet1/20
            enabled: false
            mode: access
          - name: Ethernet1/21
            enabled: false
            mode: access
          - name: Ethernet1/22
            enabled: false
            mode: access
          - name: Ethernet1/23
            enabled: false
            mode: access
          - name: Ethernet1/24
            enabled: false
            mode: access
          - name: Ethernet1/25
            enabled: false
            mode: access
          - name: Ethernet1/26
            enabled: false
            mode: access
          - name: Ethernet1/27
            enabled: false
            mode: access
          - name: Ethernet1/28
            enabled: false
            mode: access
          - name: Ethernet1/29
            enabled: false
            mode: access
          - name: Ethernet1/30
            enabled: false
            mode: access
          - name: Ethernet1/31
            enabled: false
            mode: access
          - name: Ethernet1/32
            enabled: false
            mode: access
          - name: Ethernet1/33
            enabled: false
            mode: access
          - name: Ethernet1/34
            enabled: false
            mode: access
          - name: Ethernet1/35
            enabled: false
            mode: access
          - name: Ethernet1/36
            enabled: false
            mode: access
          - name: Ethernet1/37
            enabled: false
            mode: access
          - name: Ethernet1/38
            enabled: false
            mode: access
          - name: Ethernet1/39
            enabled: false
            mode: access
          - name: Ethernet1/40
            enabled: false
            mode: access
          - name: Ethernet1/41
            enabled: false
            mode: access
          - name: Ethernet1/42
            enabled: false
            mode: access
          - name: Ethernet1/43
            enabled: false
            mode: access
          - name: Ethernet1/44
            enabled: false
            mode: access
          - name: Ethernet1/45
            enabled: false
            mode: access
          - name: Ethernet1/46
            enabled: false
            mode: access
          - name: Ethernet1/47
            enabled: false
            mode: access
          - name: Ethernet1/48
            enabled: false
            mode: access
          - name: Ethernet1/49
            enabled: false
            mode: access
          - name: Ethernet1/50
            enabled: false
            mode: access
          - name: Ethernet1/51
            enabled: false
            mode: access
          - name: Ethernet1/52
            enabled: false
            mode: access
          - name: Ethernet1/53
            enabled: false
            mode: access
          - name: Ethernet1/54
            enabled: false
            mode: access
          - name: Ethernet1/55
            enabled: false
            mode: access
          - name: Ethernet1/56
            enabled: false
            mode: access
          - name: Ethernet1/57
            enabled: false
            mode: access
          - name: Ethernet1/58
            enabled: false
            mode: access
          - name: Ethernet1/59
            enabled: false
            mode: access
          - name: Ethernet1/60
            enabled: false
            mode: access
          - name: Ethernet1/61
            enabled: false
            mode: access
          - name: Ethernet1/62
            enabled: false
            mode: access
          - name: Ethernet1/63
            enabled: false
            mode: access
          - name: Ethernet1/64
            enabled: false
            mode: access